version: "3.7"

services:
  vmq0:
    # This should work with a variety of versions, on my ARM based Mac I had problems
    # with some tags of vernemq, but those were non-existent on linux
    image: vernemq/vernemq:1.12.3-alpine
    environment:
      DOCKER_VERNEMQ_SWARM: 1
      DOCKER_VERNEMQ_ACCEPT_EULA: "yes"

      DOCKER_VERNEMQ_USER_ADMIN: "admin"
      DOCKER_VERNEMQ_PLUGINS.vmq_bridge: "on"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0: "a1vs2yekznubv1-ats.iot.eu-central-1.amazonaws.com:8883"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.cleansession: "on"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.restart_timeout: 10
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.try_private: "on"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.tls_version: "tlsv1.2"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.insecure: "on"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.cafile: "/etc/ssl/AmazonRootCA1.pem"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.certfile: "/etc/ssl/cert.pem"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.keyfile: "/etc/ssl/cert.private"
      # Send messages on all topics out
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.topic.1: "* out"
      # DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.topic.2: "demo out"
      DOCKER_VERNEMQ_VMQ_BRIDGE.ssl.sbr0.client_id: "auto"

    volumes:
      - ./local/ssl:/etc/ssl/
    ports:
      # Expose the mqtt port to the host
      - "1883:1883"
